"""Campo resopndido na tabela contato

Revision ID: 101387a8d833
Revises: 3bec2501dd4f
Create Date: 2025-06-30 12:25:32.160019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101387a8d833'
down_revision = '3bec2501dd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
