"""feat: Atualizando o db

Revision ID: 219e973b213e
Revises: 71cc33f2df91
Create Date: 2025-07-16 11:41:21.740917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219e973b213e'
down_revision = '71cc33f2df91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
