"""Add coluna data_envio

Revision ID: b1f291775c30
Revises: 1546a5aa46cb
Create Date: 2025-07-03 09:07:09.851412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f291775c30'
down_revision = '1546a5aa46cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###
